baseURL = "https://antonio-parada.github.io/plx.ie/"
languageCode = "en-us"
title = "PLX.IE - Powering Your Digital Future"
theme = "ananke"

[params]
  custom_css = ["css/custom.css"]

[menu]
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 10
  [[menu.main]]
    name = "Team"
    url = "/team/"
    weight = 20
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 30
  [[menu.main]]
    name = "Clients"
    url = "/clients/"
    weight = 40
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 45
  [[menu.main]]
    name = "Careers"
    url = "/careers/"
    weight = 46
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 50
  [[menu.main]]
    name = "Getting Started"
    url = "/docs/getting-started/"
    parent = "Docs"
    weight = 51
  [[menu.main]]
    name = "Internal Guidelines"
    url = "/docs/internal/"
    parent = "Docs"
    weight = 52
  [[menu.main]]
    name = "Operational Processes"
    url = "/docs/processes/"
    parent = "Docs"
    weight = 53
  [[menu.main]]
    name = "Security Best Practices"
    url = "/docs/security/"
    parent = "Docs"
    weight = 54
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 55
  [[menu.main]]
    name = "Finance"
    url = "/finance/"
    weight = 60
  [[menu.main]]
    name = "Investor Relations"
    url = "/finance/investor-relations/"
    parent = "Finance"
    weight = 61
  [[menu.main]]
    name = "Marketing"
    url = "/marketing/"
    weight = 70
  [[menu.main]]
    name = "Case Studies"
    url = "/marketing/case-studies/"
    parent = "Marketing"
    weight = 71
  [[menu.main]]
    name = "Press Releases"
    url = "/marketing/press-releases/"
    parent = "Marketing"
    weight = 72
  [[menu.main]]
    name = "Press Kit"
    url = "/marketing/press-kit/"
    parent = "Marketing"
    weight = 73
  [[menu.main]]
    name = "Contact Us"
    url = "/contact/"
    weight = 80

  [[menu.footer]]
    name = "Terms of Service"
    url = "/terms-of-service/"
    weight = 10
  [[menu.footer]]
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 20

[params.opengraph]
  image = "/images/plx-og-image.jpg"
  description = "PLX.IE: Powering Your Digital Future with scalable cloud infrastructure and web services."